### ISSUE TITLE
`rofl build`: Should validate "volumes" in compose.yaml

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/cli#462]
Valid
```yaml
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
```

Likely invalid
```yaml
    volumes:
      - /home/luka/app:/app
```

**Comment by kostko** [comment]
Yes, you need to declare persistent volumes something like this to get them placed in the right directory automatically:
```yaml
services:
  myservice:
    # ...
    volumes:
      - my-volume:/foo

volumes:
  my-volume:
```

But in theory you can bind any path currently.
